name: flutter_news_app

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  cached_network_image: ^3.1.1
  flutter_bloc: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/